Repository rathesDot/rathes.me, pull requests merged in 2020-01, with the labels that each got.

#213 Feature: Reading list 2020
  src/pages/about.js
Labels: enhancement

#215 Refactor: BlogList
  src/components/BlogList/BlogList.js
  src/pages/writings.js
Labels: enhancement

#216 Feature: Introduce Styled Components
  gatsby-config.js
  package.json
  src/components/BlogList/BlogList.js
  src/content/articles/en/review-2019.mdx
  src/pages/writings.js
  yarn.lock
Labels: bug, enhancement

#217 Refactor: Styled Components theme
  src/components/BlogList/BlogList.js
  src/components/Layout/index.js
  theme.js
Labels: enhancement

#218 Feature: `TextSmall` component
  src/components/BlogList/BlogList.js
  src/components/Footer/index.js
  src/components/OverviewInfo/index.js
  src/components/Typography/TextSmall.js
  src/components/Typography/index.js
  theme.js
Labels: enhancement

#219 Feature: `Link` component
  package.json
  src/components/BlogList/BlogList.js
  src/components/Link/Link.js
  src/components/Link/index.js
  src/components/Navigation/index.js
  src/components/OverviewInfo/index.js
  src/components/ReadingList/ReadingList.js
  src/components/SayHi/index.js
  src/pages/404.js
  src/pages/legal.js
  src/pages/work.js
  src/pages/writings.js
  src/templates/Blog/mdx.js
  src/templates/Blog/remark.js
  yarn.lock
Labels: enhancement

#224 :one: Mention team ONE
  src/pages/about.js
Labels: enhancement

#230 Improve: Mobile Sizes
  src/components/Layout/index.js
  src/components/Navigation/index.js
  src/pages/index.js
Labels: enhancement

#231 🖋 Improve Grammar
  src/pages/about.js
Labels: enhancement

#233 🐛 Fixes that wrong test data set was removed
  src/utils/index.spec.js
Labels: bug

#234 Fix: Year 2020
  LICENSE
  src/components/Footer/index.js
Labels: bug

#236 Feature: Abstracts
  src/pages/talks/managing-time.js
  src/pages/talks/meetings.js
  src/pages/work.js
Labels: enhancement

#237 Update the readinglist
  src/pages/about.js
Labels: enhancement

#238 Refactor: Remove TailwindCSS
  README.md
  gatsby-config.js
  package.json
  postcss.config.js
  src/components/Layout/global.js
  src/components/Layout/index.js
  src/components/Layout/styles.css
  src/pages/index.js
  src/pages/work.js
  tailwind.config.js
  yarn.lock
Labels: enhancement

#235 Update/job
  src/components/OverviewInfo/index.js
  src/components/Separator/Separator.js
  src/content/articles/en/writing-new-chapters-in-life.mdx
  src/content/files/resume.pdf
  src/content/images/blog/writing.jpg
  src/pages/about.js
  src/pages/work.js
Labels: enhancement
